### ISSUE TITLE
Add FreeBSD support

### ISSUE THREAD

**Issue by tuaris** [danstiner/rust-u2f#30]
How much effort would it take to add in support for FreeBSD?  I can take care of the packaging and rc scripting part of it.

**Comment by danstiner** [comment]
I've never actually worked on a BSD system, so sorry but I can't say. I would guess the three things that may need addressed would be:
- How to emulate a USB device (this is a virtual "hardware" token after all)
- How to communicate between the daemon running as root and the user's session (I use systemd to set up a socket and run a per-user daemon that connects to it currently)
- How to pop a notification for the user to confirm/deny (currently relies on DBus, similar to libnotify)

**Comment by KOLANICH** [comment]
IMHO we need an API to create software authenticators without perversions.

https://bugzilla.mozilla.org/show_bug.cgi?id=1526792
https://github.com/w3c/webauthn/issues/1157
https://github.com/ghacksuserjs/ghacks-user.js/issues/644

**Comment by danstiner** [comment]
@KOLANICH this issue is about FreeBSD support, if you want to discuss the Webauthn spec itself please kindly do so somewhere else.

@tuaris to be more clear, I'm not planning to try and support BSD, but if you want to fork the project go right ahead! But since I'm not planning to add support myself I'm going to close this issue.
