### ISSUE TITLE
Passwordless is not implemented

### ISSUE THREAD

**Issue by terrence-h1974** [danstiner/rust-u2f#39]
Passwordless is not (yet) implemented.

**Comment by danstiner** [comment]
Sorry but I am not planning to implement the new Webauthn specification anytime soon both because of the time investment required and because I'm not comfortable with the current secret storage mechanism (a file on disk) being secure enough to fully replace passwords.

I would be open to contributions to that effect if a more secure secret storage mechanism is implemented, perhaps on the GNOME keyring or in the TPM co-processor.

**Comment by terrence-h1974** [comment]
Tried WebAuthn on other websites. It worked (on one website, there was an issue about origin, most likely website issue).

**Comment by danstiner** [comment]
Good to know, probably on other sites they are not checking if Webauthn is falling back to U2F protocol and just happily allow login. In my opinion the Yubico test site is doing the proper thing by *not* allowing U2F tokens to be the sole auth factor. U2F hardware is designed to be a second factor, not the only factor.

**Comment by andy-dicki** [comment]
How are U2F and WebAuthn different?
