### ISSUE TITLE
SoftU2F is not detected as USB device

### ISSUE THREAD

**Issue by andy-dicki** [danstiner/rust-u2f#45]
SoftU2F is not detected as USB device, but in dmesg it is an "USB HID" device.

**Comment by danstiner** [comment]
Ahh okay this actually makes sense and is expected behavior but I had never thought about it.

I use the Linux UHID driver to create a virtual HID device.  You can think of USB HID as a separate protocol only certain USB devices support. Since this UHID devices do not support the full USB protocol, the kernel does not expose them as a USB devices.

**Comment by danstiner** [comment]
Closing as expected behavior.
