### ISSUE TITLE
Daemon doesn't start on Arch

### ISSUE THREAD

**Issue by lmarianski** [danstiner/rust-u2f#69]
i'm running `systemctl --user start softu2f`
and i get
```
Sep 29 20:55:26.998 INFO Starting software Universal 2nd Factor device user daemon, version: 0.4.0
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by danstiner** [comment]
Hi Łukasz, the error could certainly be more clear but probably the userspace daemon is having trouble connecting to `/run/softu2f/softu2f.sock` because it doesn't exist.

Are you using the arch packages from https://aur.archlinux.org/packages/softu2f/ that grawity created? They should set everything up correctly (i.e.normally systemd manages that socket per https://github.com/danstiner/rust-u2f/blob/master/linux/system-daemon/softu2f.socket)

**Comment by andrewkdinh** [comment]
Same thing here. Solved the problem by removing the old files and manually building

**Comment by danstiner** [comment]
Thanks Andrew, glad to hear that worked for you! Were the old files from the package grawity created? Curious if it needs some touch up.

I don't use Arch so feedback is helpful, it's difficult for me to debug without better logs. Generally the issue is an unsupported display manager or some conflicting packages.

**Comment by andrewkdinh** [comment]
Sorry, don’t really know what you mean by the first question. 

I built from the latest master, and I had the same initial error as @lmarianski  in which `/run/softu2f/softu2f.sock` didn’t exist

**Comment by danstiner** [comment]
Thanks, that actually does answer my question!

I suspect for some reason `systemd-tmpfiles` is not picking up the config right away to create `/run/softu2f/softu2f.sock`, possibly an extra command in the makefile to force it to reload immediately would fix it. Arch is a bit of pain to setup but I may experiment at some point out of curiosity, but no promises, especially since things are working for you.

**Comment by ElArtista** [comment]
Just bumped into the same issue!
When running just `systemctl --user start softu2f` I get the above error (indicating that `/run/soft2uf/softu2f.sock` is missing). I noticed that `system-daemon/softu2f-tmpfiles.conf`only creates the `/run/softu2f/` folder, the actual socket file is created by `system-daemon/softu2f.socket`. Thus running the user service directly for softu2f will not create the needed socket. I'm not sure what the actual usage should be here, I managed to make it run by first manually starting the system socket using:
```
sudo systemctl start softu2f.socket
```
and then starting the user service with
```
systemctl --user start softu2f
```
Either the README instructions need to be updated, or some kind of socket systemd unit must be made for the relevant user service too?

**Comment by danstiner** [comment]
Interesting, I think you found the issue @ElArtista. Looking quick at the Arch package @grawity made it installs the systemd definitions but does not enable or start `softu2f.socket`. 

If you can confirm that the following commands fix things permanently I'll add them to the README. I'm not going to take on maintaining the Arch package but if you want to reach out to @grawity and improve it that'd be great as well.

```
systemctl --system enable softu2f.socket
systemctl --system start softu2f.socket
systemctl --user enable softu2f.service
systemctl --user start softu2f.service
```

**Comment by grawity** [comment]
It should be fine to enable system/softu2f.socket via preset, but generally Arch packages avoid automatically starting daemons.

But since user/softu2f.service is neither socket-activated nor D-Bus-activated, I don't really want to `--global enable` it... Besides that, there's no way from a package to automatically *start* a user unit after installation.

pacman already invokes systemd-tmpfiles on changes, so there's nothing special to do for that.

**Comment by danstiner** [comment]
Thanks grawity, that all makes sense! I'll update the README on this side and enabling the system socket service via preset makes sense to me.

I faced the same issue with not being able to start a user unit after installation on debian/fedora, but it would be weird if installing a package somehow reached into all active sessions and started a user process for them haha

**Comment by danstiner** [comment]
Looks like the Arch package maintainers didn't like that change! I'll at least update the README over here
