### ISSUE TITLE
[Feature] Run without systemd (e.g. in Docker container)

### ISSUE THREAD

**Issue by Niek** [danstiner/rust-u2f#84]
Would it be possible to add support to rust-u2f to run on non-systemd platforms? The reason I'm asking is that I would love to run this in a Docker container, which normally don't support systemd/dbus.

**Comment by danstiner** [comment]
Hi Niek, I should document the architecture better, but tl;dr you are correct the userspace daemon depends on dbus/libnotify to show an approval prompt to the user.

systemd is not technically needed, you can create a pipe manually and then bind the system daemon to one end (https://github.com/danstiner/rust-u2f/blob/c62b34f469e3aae8b72fbc284181de9d88c547d0/linux/system-daemon/src/main.rs#L80-84) and the user daemon to the other end. I do this for testing sometimes.

The other issue is UHID, which this program uses to create a virtual USB device. I doubt containers have access to that API (/dev/uhid) by default, and even if you allowed access I doubt it is namespaced in the kernel, meaning every container would see every virtual U2F device created.

So I'm curious of the use case. Splitting into user/system daemons was very much to support the desktop GUI use case and probably makes it harder to apply this tool to your use case. One approach would be to maybe run the system daemon outside the containers under systemd, then give contains access to the rust-u2f socket to create virtual devices (/var/run/softu2f or something similar). That has security implications but docker isn't really a security solution anyways and I assume this is for testing purposes. You'd have to update the user daemon to check for approval in a different way than dbus, but I'd accept a PR adding a new method behind a command line flag that prompted for a yes/no on `stdin` or similar. It'd be useful for testing anyways.

Aside: my initial prototype (https://github.com/danstiner/rust-u2f/tree/c29529e9d89be9e543c3c95964f6dec4c6164c05/softu2f-bin) was an all-in-one tool that had to be run as root (in order to open /dev/uhid) that did approval by reading from stdin. However it was not practical for me because switching away from chrometo type `yes` into the terminal would cancel the u2f flow, Chrome actually explicitly checks focus stays on it during the approval process. That anecdote and old code might or might not be useful to you, dunno but good luck.

**Comment by Niek** [comment]
Thanks for the extensive reply, @danstiner! You are right, my use-case is probably too exotic/out of scope for rust-u2f. Thanks for providing the initial prototype commit hash, I think I'm able to make something based on this code. I'll close this issue now.
